### ISSUE TITLE
Incorrect password throws error

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover-cli#13]
When I deploy an app and the auth token is no longer valid, it prompts for a password.  If I type it in wrong, it doesn't fail gracefully with a polite message, it gives the following unhandled promise rejection error message:

	(node:3095) UnhandledPromiseRejectionWarning: Error: Password is incorrect.
		at ErrorFactory.createError (/usr/lib/node_modules/caprover/built/utils/ErrorFactory.js:19:17)
		at /usr/lib/node_modules/caprover/built/api/HttpClient.js:68:50
	(node:3095) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
	(node:3095) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Hazzard17h** [comment]
I think this is resolved from #16
