### ISSUE TITLE
Fresh installation, but 1000 : Parser Failed. See internal logs on Monitoring

### ISSUE THREAD

**Issue by tsaqib** [caprover/caprover-cli#41]
A freshly installed CapRover v1.5.2 shows _1000 : Parser Failed. See internal logs_ when navigated to **Monitoring** tab. The stacktrace is as below: 

TypeError: Cannot read property 'trim' of undefined
at Request._callback (/usr/src/app/built/user/system/LoadBalancerManager.js:255:75)
at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
at Request.emit (events.js:198:13)
at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1161:10)
at Request.emit (events.js:198:13)
at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:286:20)
at IncomingMessage.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1129:12)
at process._tickCallback (internal/process/next_tick.js:63:19)

Error: Parser Failed. See internal logs...
at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:7:16)
GET /api/v2/user/system/loadbalancerinfo 304 2.769 ms - -
at Request._callback (/usr/src/app/built/user/system/LoadBalancerManager.js:266:43)
at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
at Request.emit (events.js:198:13)
at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1161:10)
at Request.emit (events.js:198:13)
at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:286:20)
at IncomingMessage.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1129:12)

**Comment by githubsaturn** [comment]
Is this a CLI bug? Or the dashboard bug?


If it's on dashboard, please provide your OS and VPS provider.

**Comment by tsaqib** [comment]
A dashboard bug on AWS EC2 (Ubuntu 18.04.3 LTS).

**Comment by githubsaturn** [comment]
Moving this issue to the main project.
